<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * @file
 * Add a field to an existing form.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */

function nitinaxlrnt_form_system_site_information_settings_alter(&$form, $form_state)
{

    $siteapikey = \Drupal::config('nitinaxlrnt.settings')->get('siteapikey');
    $form['siteapikey'] = array(
        '#type' => 'textfield',
        '#title' => t("Site API Key."),
        '#default_value' => isset($siteapikey)&&!empty($siteapikey)? $siteapikey : "No API Key yet",
        '#placeholder' => "No API Key yet",
    );
    if($siteapikey!=""){
        $form['actions']['submit']['#value'] = t('Update Configuration');
    }

    foreach (array_keys($form['actions']) as $action) {
        if (isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
            $form['actions'][$action]['#submit'][] = 'nitinaxlrnt_site_information_submit';
        }
    }

}

function nitinaxlrnt_site_information_submit(array $form, FormStateInterface &$form_state)
{
    $siteapikey = \Drupal::config('nitinaxlrnt.settings')->get('siteapikey');  
    $siteapikey_new = $form_state->getvalue('siteapikey');
    if($siteapikey_new != $siteapikey){
      $config = \Drupal::service('config.factory')->getEditable('nitinaxlrnt.settings');
      $config->set('siteapikey', $siteapikey_new)->save();
      drupal_set_message(t('Site API Key has been saved with '.$siteapikey_new));
    }
    

}
